### ISSUE TITLE
爬蟲某些字無法正確爬完-Hitcon Zeroday

### ISSUE THREAD

**Issue by newbuy** [seadog007/request-list#6]
https://gist.github.com/seadog007/3ad6c54916796aa495bb4525c1560f8b

1.https://zeroday.hitcon.org/vulnerability/ZD-2017-00003
名稱內含有"&"，未正確爬完

2.https://zeroday.hitcon.org/vulnerability/ZD-2017-00049
描述內含有單引號，未正確爬完

**Comment by seadog007** [comment]
Thanks for reporing. Fixed
